<?php
/*
 * 标题：设计师网址导航
 * 日期：2015-01-15
 * 作者：admin@289w.com
 * 网址：www.289w.com
 */
 
return array(
	'host'        => '域名',
	'logo'        => 'Logo',
	'keywords'    => '关键词',
	'description' => '描述',
	'bottom'      => '底部',
	'icp'         => 'ICP 备案号',
	
	'panel'       => '后台',
	'index'       => '首页',
	'item'        => '项目',
	'tags'        => '标签',
	'title'       => '标题',
	'brief'       => '简介',
	'content'     => '内容',
	'system'      => '系统',
	'platform'    => '平台',
	'info'        => '信息',
	'setting'     => '设置',
	'menu'        => '栏目',
	'extend'      => '扩展',
	'nav'         => '导航',
	'guestbook'   => '在线留言',
	'reply'       => '回复',
	'icon'        => '图标',
	'count'       => '统计',
	'click'       => '点击',

	'id'          => 'ID',
	'manage'      => '管理',
	'category'    => '分类',
	'basic'       => '基本',
	'breadclumb'  => '当前位置',

	'news'        => '公告',
	'notice'      => '须知',	
	'role'        => '角色',
	'username'    => '用户名',
	'password'    => '密码',
	'realname'    => '姓名',
	'nickname'    => '昵称',
	'name'        => '名称',
	'alias'       => '别名',
	'idcard'      => '身份证',
	'upload'      => '上传',
	'us'          => '我们',
	
	'my'          => '我的',
	'account'     => '账号',
	'user'        => '用户',
	'admin'       => '管理员',
	'bind'        => '绑定',
	'type'		  => '类型',
	'record'	  => '记录',
	'message'	  => '消息',
	'check'       => '审核',
	'article'       => '文章',
	
	'friend'      => '友情',
	'link'        => '链接',
	'advert'      => '广告',
	'slideshow'   => '幻灯片',
	'recommend'   => '推荐',

	'theme'      => '主题',
	'action'     => '操作',
	'add'        => '添加',
	'create'     => '创建',
	'release'    => '发布',
	'delete'     => '删除',
	'edit'       => '编辑',
	'modify'     => '修改',
	'copy'       => '复制',
	'view'       => '查看',
	'list'       => '列表',
	'group'      => '分组',
    'submit'     => '提交',
	'goback'     => '返回',	
	'reset'      => '重置',	
    'download'   => '下载',
	'backup'     => '备份',
	'search'     => '搜索', 
	'query'      => '查询', 
	'image'      => '图片', 
	'details'    => '详细',
	'other'      => '其它',
	'contact'    => '联系',
	'current'    => '当前',
	'select'     => '选择',
	'belong'     => '所属',
	'module'     => '模型',
	'sub'        => '副',
	
	'colon'      => '：',
	'comma'      => '，',
	'qmark'      => '？',
	'or'         => '或',
	'need'       => '须',
	'to'         => '至',
	'please'     => '请',
	'before'     => '前',
	'total'      => '总',
	'new'        => '新',
	'already'    => '已',
	'not'        => '未',
	'nothing'    => '无',
	'this'       => '该',
	'number'     => '编号',
	'more'       => '更多',
	'all'        => '所有',
    'ok'         => '正常',
	'confirm'    => '确认',
	'cancel'     => '取消',
	'error'      => '错误',
	'status'     => '状态', 
	'on'         => '启用', 
	'off'        => '禁用', 
	'show'       => '显示',
	'hide'       => '隐藏',
	'auth'       => '权限',
	'sort'       => '分类',
	'sortorder'  => '排序',
	'remark'     => '备注',
	'start'      => '开始',
	'cache'      => '缓存',
	'help'       => '帮助', 
	'document'   => '文档', 
	'end'        => '结束',
	'server'     => '服务',
	'signature'  => '签名',
	'send'       => '发送',
	'port'       => '端口',
	'latest'     => '最新',
	'footer'     => '网站底部',
	
	'success'    => '成功',
	'failure'    => '失败',

	'region'     => '地区',
    'province'   => '省份',
	'city'       => '城市',
    'date'       => '日期',
	'time'       => '时间',
    'mobile'     => '手机',
    'phone'      => '电话',
	'address'    => '地址',
	'mail'       => '邮件',
	'website'    => '网站',
	'email'      => '电子邮箱',

	'import'      => '导入',
	'export'      => '导出',
	
    'register'    => '注册',
    'login'       => '登录',
    'logout'      => '退出',
    'last'        => '上次',
	
	'hello'         => '您好！',
	'loading'       => '加载中，请稍候...',
	'ajaxError'     => '网络连接不正常或服务器错误，请重新登陆后再试！',
	
	'copyRight'      => 'Copyright © 2014 &nbsp;<a href="http://www.289w.com" class="link" target="_blank">www.289w.com</a>&nbsp; All Rights Reserved.',
);
?>